const king_black = '<div class="piece" id="king"><img class="imgPiece"src="./img/pieces/king_black.png"alt="king"></div>'
const queen_black = '<div class="piece" id="queen"><img class="imgPiece"src="./img/pieces/queen_black.png"alt="queen"></div>'
const rook_black = '<div class="piece" id="rook"><img class="imgPiece"src="./img/pieces/rook_black.png"alt="rook"></div>'
const bishop_black = '<div class="piece" id="bishop"><img class="imgPiece"src="./img/pieces/bishop_black.png"alt="bishop"></div>'
const knight_black = '<div class="piece" id="knight"><img class="imgPiece"src="./img/pieces/knight_black.png"alt="knight"></div>'
const pawn_black = '<div class="piece" id="pawn"><img class="imgPiece"src="./img/pieces/pawn_black.png"alt="pawn"></div>'

const king_white = '<div class="piece" id="king"><img class="imgPiece"src="./img/pieces/king_white.png"alt="king"></div>'
const queen_white = '<div class="piece" id="queen"><img class="imgPiece"src="./img/pieces/queen_white.png"alt="queen"></div>'
const rook_white = '<div class="piece" id="rook"><img class="imgPiece"src="./img/pieces/rook_white.png"alt="rook"></div>'
const bishop_white = '<div class="piece" id="bishop"><img class="imgPiece"src="./img/pieces/bishop_white.png"alt="bishop"></div>'
const knight_white = '<div class="piece" id="knight"><img class="imgPiece"src="./img/pieces/knight_white.png"alt="knight"></div>'
const pawn_white = '<div class="piece" id="pawn"><img class="imgPiece"src="./img/pieces/pawn_white.png"alt="pawn"></div>'

const king_green = '<div class="piece" id="king"><img class="imgPiece"src="./img/pieces/king_green.png"alt="king"></div>'
const queen_green = '<div class="piece" id="queen"><img class="imgPiece"src="./img/pieces/queen_green.png"alt="queen"></div>'
const rook_green = '<div class="piece" id="rook"><img class="imgPiece"src="./img/pieces/rook_green.png"alt="rook"></div>'
const bishop_green = '<div class="piece" id="bishop"><img class="imgPiece"src="./img/pieces/bishop_green.png"alt="bishop"></div>'
const knight_green = '<div class="piece" id="knight"><img class="imgPiece"src="./img/pieces/knight_green.png"alt="knight"></div>'
const pawn_green = '<div class="piece" id="pawn"><img class="imgPiece"src="./img/pieces/pawn_green.png"alt="pawn"></div>'

const king_purple = '<div class="piece" id="king"><img class="imgPiece"src="./img/pieces/king_purple.png"alt="king"></div>'
const queen_purple = '<div class="piece" id="queen"><img class="imgPiece"src="./img/pieces/queen_purple.png"alt="queen"></div>'
const rook_purple = '<div class="piece" id="rook"><img class="imgPiece"src="./img/pieces/rook_purple.png"alt="rook"></div>'
const bishop_purple = '<div class="piece" id="bishop"><img class="imgPiece"src="./img/pieces/bishop_purple.png"alt="bishop"></div>'
const knight_purple = '<div class="piece" id="knight"><img class="imgPiece"src="./img/pieces/knight_purple.png"alt="knight"></div>'
const pawn_purple = '<div class="piece" id="pawn"><img class="imgPiece"src="./img/pieces/pawn_purple.png"alt="pawn"></div>'